# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbassignment2', '0002_auto_20171027_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedby',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
