# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dbassignment2', '0004_remove_purchasedby_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedby',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
